# Generated by Django 5.1.7 on 2025-03-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HakemDegerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakem_eposta', models.EmailField(max_length=254, verbose_name='Hakem E-posta')),
                ('anonim_makale', models.FileField(upload_to='hakem_makaleler/', verbose_name='Anonimleştirilmiş Makale')),
                ('degerlendirme', models.TextField(blank=True, null=True, verbose_name='Hakem Değerlendirme')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Ek Açıklama')),
                ('son_hali', models.FileField(blank=True, null=True, upload_to='son_makaleler/', verbose_name='Son Değerlendirme Makalesi')),
                ('ilgi_alanlari', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Makaleler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_no', models.CharField(max_length=20, unique=True, verbose_name='Takip Numarası')),
                ('yazar_eposta', models.EmailField(max_length=254, verbose_name='Yazar E-posta')),
                ('orijinal_dosya', models.FileField(upload_to='makaleler/', verbose_name='Orijinal Makale')),
                ('anonim_makale', models.FileField(blank=True, null=True, upload_to='anonim_makaleler/', verbose_name='Anonimleştirilmiş Makale')),
                ('hakem_eposta', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Atanan Hakem E-posta')),
                ('durum', models.CharField(choices=[('incelemede', 'İncelemede'), ('hakemde', 'Hakeme Atandı'), ('revizyon', 'Revizyon Bekleniyor'), ('yayınlandı', 'Yayınlandı'), ('reddedildi', 'Reddedildi')], default='incelemede', max_length=20, verbose_name='Makale Durumu')),
                ('alan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Atanan Alan')),
                ('yazar_bilgileri', models.TextField(blank=True, null=True, verbose_name='Tespit Edilen Yazarlar')),
                ('kurum_bilgileri', models.TextField(blank=True, null=True, verbose_name='Tespit Edilen Kurumlar')),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_no', models.CharField(max_length=20, verbose_name='Makale Takip Numarası')),
                ('gonderen_eposta', models.EmailField(max_length=254, verbose_name='Gönderen E-posta')),
                ('mesaj', models.TextField(verbose_name='Mesaj İçeriği')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='EditorAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editör_eposta', models.EmailField(max_length=254, verbose_name='Editör E-posta')),
                ('hakem_eposta', models.EmailField(max_length=254, verbose_name='Atanan Hakem')),
                ('atama_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Atama Tarihi')),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makaleler', verbose_name='Makale')),
            ],
        ),
    ]
